using System.Text;

namespace ChillipommesGenerator.Core.Dictionaries
{
    public sealed class PartDictionary
    {
        public static byte[] PROPERTY_PART => Encoding.UTF8.GetBytes("{get;set;}");

        public static byte[] TO_STRING_PART => Encoding.UTF8.GetBytes("public override string ToString(){return base.ToString();}");

        public static byte[] EQUALS_PART => Encoding.UTF8.GetBytes("public override bool Equals(object obj){return base.Equals(obj);}");

        public static byte[] GET_HASH_PART => Encoding.UTF8.GetBytes("public override int GetHashCode(){return base.GetHashCode();}");

        public static byte[] CLASS_COMMENT_PART => Encoding.UTF8.GetBytes("//This class is autogenerated by ChillipommesGenerator");
    }
}
